### ISSUE TITLE
Please target .net 4.6

### ISSUE THREAD

**Issue by TristinDavis** [IdentityServer/IdentityServer3.Admin.EntityFramework#1]
I get the following when installing the 1.0.0-beta1:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'IdentityServer3.Admin 1.0.0-beta1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by iBoonz** [comment]
This is because the package has a TargetFramework of 4.5.
I removed it, try it again 
Install-Package IdentityServer3.Admin -Pre

**Comment by TristinDavis** [comment]
That worked for the IdentityServer3.Admin package. Can you do the same thing for the IdentityServer3.Admin.EntityFramework package also, please.

**Comment by dajomo** [comment]
I have the same issue, but my warning is with v4.5

**Comment by leastprivilege** [comment]
the target should be 4.5.2

**Comment by iBoonz** [comment]
Ty @leastprivilege , changed the target to 4.5.2
