### ISSUE TITLE
Duplicate type with name 'System.Web.Http.Properties.System.Web.Http.CommonWebApiResources' in assembly 'IdentityServer3.Admin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

### ISSUE THREAD

**Issue by AbandonedSoul** [IdentityServer/IdentityServer3.Admin.EntityFramework#10]
I've installed IdentityServer3.Admin.EntityFramework 1.0.0-beta5 via nuget and I'm getting the above error when I start application.

**Comment by iBoonz** [comment]
Hi, I am aware of this issue, this is already solved in the git repo, ijust need to build a new nuget package. i am also updating the project with the new Identityserver3.Entityframwork binaries.

This will normally be resolved in a couple of days

**Comment by iBoonz** [comment]
solved
