### ISSUE TITLE
UI shows up, but nothing seems to work.

### ISSUE THREAD

**Issue by kwaxi** [IdentityServer/IdentityServer3.Admin.EntityFramework#15]
I'm trying to configure the IdentityAdmin w/ EntityFramework but somehow I can't work it out.

I've created a custom IdentityAdminService class, like in the Host example

```csharp
public class IdentityAdminManagerService : IdentityAdminCoreManager<IdentityClient, int, IdentityScope, int>
{
  public IdentityAdminManagerService(string connectionString)
    : base(connectionString)
    {
    }
}
```

and using it in the Startup.cs as follows:

```csharp
var factory = new IdentityAdminServiceFactory
{
  IdentityAdminService = new Registration<IIdentityAdminService, IdentityAdminManagerService>(configurationDbConnectionStringName)
};
```

When browsing to the application the IdentityAdmin UI shows up, but I can't do anything there and also the already configured clients and scopes aren't visble.

Can you give me a hint where to look further?

**Comment by madhavabhyankar** [comment]
Check [this](https://github.com/madhavabhyankar/IdentityServerWithWindowsAuthWSFed) out.  That has WSFed - which you dont need.
