### ISSUE TITLE
Problem with admin log in from remote machine

### ISSUE THREAD

**Issue by lef-teris** [IdentityServer/IdentityServer3.Admin.EntityFramework#17]
Hello, we are dealing with the following problem:

We have downloaded the project, updated its nuget packages to latest (specifically for IdentityServer3 version 2.5.0). We added the test ssl that you provide (idsrv3test.pfx) but we are having an issue when we try to login if the application runs on a remote machine. The application starts normal and after clicking on the login button we get a blank page due to an authorization error.

There is no problem if we run the application from a local machine. 

Do you have any idea why is it happening and how to fix it? If the problem is because of the ssl can we disable it?

Thanks in advance.

**Comment by iBoonz** [comment]
I suspect you cannot use the test pfx on a production enviroment.

**Comment by madhavabhyankar** [comment]
Is it possible to share your code?
