### ISSUE TITLE
Nuget Package

### ISSUE THREAD

**Issue by kathrine0** [IdentityServer/IdentityServer3.Admin.EntityFramework#2]
Hello,
I've downloaded these sources and I tried to replace IdentityServer3.Admin.EntityFramework (core) project with the nuget found here: https://www.nuget.org/packages/IdentityServer3.Admin.EntityFramework/1.0.0-beta3.
However, it seems not to be working. Can you give me any tips where do I find a working nuget?
Thank you,

**Comment by iBoonz** [comment]
What exactly is not working? What error are you getting?

**Comment by kathrine0** [comment]
Hey, I solved my problems by manually adding configuration to packages.config and .csproj files. Somehow nuget did not do that automatically.
Also, there is missing Automapper dependency which is resolved by manually installing Automapper package.

**Comment by iBoonz** [comment]
@brockallen, is it possible to publish a new nuget package?

**Comment by brockallen** [comment]
NuGet now updated
