### ISSUE TITLE
Create DB objects in a specific schema

### ISSUE THREAD

**Issue by fcartu** [IdentityServer/IdentityServer3.Admin.EntityFramework#20]
There is any possibility to modify the default DB schema for admin db objects? @brockallen @leastprivilege

**Comment by brockallen** [comment]
Do we not have an option for that @iBoonz?

**Comment by iBoonz** [comment]
You can add your own schema in the IdentityAdminCoreManager constructor, [Code](IdentityAdminCoreManager)

**Comment by fcartu** [comment]
Thanks @iBoonz @brockallen, I was using beta6.
