### ISSUE TITLE
Securing Admin App

### ISSUE THREAD

**Issue by a2dude** [IdentityServer/IdentityServer3.Admin.EntityFramework#22]
I'm looking for best practice guidance wrt securing the admin app in a production environment.  Any pointers?

It occurs to me that I can run a single instance of the admin app and manage multiple different environments by mapping each environment to a different path.  Is this practical or wise?

**Comment by madhavabhyankar** [comment]
I think this question should be posted on "https://github.com/IdentityServer/IdentityServer3.Admin".
