### ISSUE TITLE
Bug in QueryScopesAsync()?

### ISSUE THREAD

**Issue by wolfwaters** [IdentityServer/IdentityServer3.Admin.EntityFramework#23]
In IdentityAdminCoreManager.cs, method QueryScopesAsync(), I find these lines:

                        var scope = new ScopeSummary
                        {
                            Subject = x.Id.ToString(),
                            Name = x.Name,
                            Description = x.Name
                        };

I guess it is by accident that you copy the scope's name to both summary's name AND description, right?

**Comment by brockallen** [comment]
Possibly.

**Comment by iBoonz** [comment]
Woops :), will fix it :)

**Comment by iBoonz** [comment]
Fixed, will be available in 1.0.0-beta8
