### ISSUE TITLE
ConnectionString from Web.Config

### ISSUE THREAD

**Issue by digitarenet** [IdentityServer/IdentityServer3.Admin.EntityFramework#24]
In the file /source/Host/Config/IdentityAdminManagerService.cs you use the connection string NAME instead of complete Connection String...It's correct? because it doesn't work with the connection string NAME (in this case "IdSvr3ConfigAdmin").

I think that in IdentityAdminCoreManager constructor should read connection string from Web.Config...instead it pass to the factory the Connection String NAME...!?!?

```
public IdentityAdminManagerService()
            : base("IdSvr3ConfigAdmin")
        {
}
```

Is this correct or I missing something in my configuration?
Where to set correct connection string to DB..?
Thanks

**Comment by iBoonz** [comment]
Hi, It is normal to use the name instead of the full connection string, this is correct.
You can find more information via : [MSDN](https://msdn.microsoft.com/en-us/data/jj592674.aspx)
