### ISSUE TITLE
IdentityServer3 Version

### ISSUE THREAD

**Issue by kathrine0** [IdentityServer/IdentityServer3.Admin.EntityFramework#3]
Hello.
This library seems to be not working with newest IdentityServer3 version 2.3.0. Is there any possibility to upgrade library dependencies? Also, current Entity Model is not cooperating with new IdentityServer3. "LogoutSessionRequired" field in IdentityClient Entity Class is missing.
Thank you

**Comment by iBoonz** [comment]
Hi @kathrine0, thanks for the update, I was unaware of these changes, I added some integration testing, similar of the IdentityServer.EntityFramework project.
I also updated the dependencies to the latest version,

**Comment by kathrine0** [comment]
Great, thank you for the changes :) Is there also any chance for nuget update?

**Comment by brockallen** [comment]
We're working on the build system -- once that's complete, doing NuGets will be much easier/faster. So soon.
