### ISSUE TITLE
The type 'IIdentityAdminService' is defined in an assembly that is not referenced. You must add a reference to assembly 'IdentityAdmin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

### ISSUE THREAD

**Issue by FabienDehopre** [IdentityServer/IdentityServer3.Admin.EntityFramework#9]
the type ```IdentityAdminCoreManager``` implements the interface ```IIdentityAdminService``` which cannot be found.

I use the packages "IdentityServer3.Admin" 1.0.0-beta6 and "IdentityServer3.Admin.EntityFramework" 1.0.0-beta5.
I check if there was an update but didn't find any.

Is there something I do wrong?

**Comment by iBoonz** [comment]
Hi, I am aware of this issue, this is already solved in the git repo, ijust need to build a new nuget package. i am also updating the project with the new Identityserver3.Entityframwork binaries.

This will normally be resolved in a couple of days
